name: Test Decode
on: push

jobs:
  decode_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Decode API Spec
        run: |
          echo "${{ secrets.BIGSECRET }}" > sec.yaml || echo "Writing failed"
          size=$(wc -c <"sec.yaml")
          echo "Size of the secret contents: $size bytes"
          
        env:
          API_SPEC: ${{ secrets.BIGSECRET }}

      - name: Log the size of the secret contents
        run: |
          base64 -d sec.yaml  > api_spec.yaml || echo "Decoding failed"
          size=$(wc -c <"api_spec.yaml")
          echo "Size of the decoded contents: $size bytes"

      - name: Encode the file with base64
        run: |
          base64 -w 0 api_spec.yaml > api_spec.base64 || echo "Encoding failed"
          jq . api_spec.yaml > api_spec_pretty.yaml || echo "Pretty printing failed"

      - name: Set the size and time taken as output parameters
        run: |
          size=$(wc -c <"api_spec.yaml")
          echo "size=$size"             >> $GITHUB_STEP_SUMMARY
      - name: Upload decoded file
        uses: actions/upload-artifact@v2
        with:
          name: api-spec
          path: api_spec_pretty.yaml