name: Test Decode
on: push

jobs:
  decode_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Decode OpenAPI schema
        id: decode
        env:
          API_SPEC: ${{ secrets.BIGSECRET }}
        run: |
          # Start the timer
          start_time=$(date +%s)

          # Decode the secret and save it to a file
          echo "${{ API_SPEC }}" | base64 --decode > api_spec.yaml

          # Log the size of the secret contents
          size=$(wc -c <"api_spec.yaml")
          echo "Size of the secret contents: $size bytes"

          # Encode the file with base64
          base64 -w 0 api_spec.yaml > api_spec.base64

          # Calculate and print the time taken
          end_time=$(date +%s)
          time_taken=$((end_time - start_time))
          echo "Time taken: $time_taken seconds"

          # Set the size and time taken as output parameters
          echo "size=$size"             >> $GITHUB_STEP_SUMMARY
          echo "time_taken=$time_taken" >> $GITHUB_STEP_SUMMARY
      - name: Print summary
        run: |
          echo "Size of the secret contents: ${{ steps.encode.outputs.size }} bytes"
          echo "Time taken to decode the schema: ${{ steps.encode.outputs.time_taken }} seconds"